conda/infrastructure

.github/workflows/boards.yml
See https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#example-using-a-public-action-in-a-subdirectory
=> GHA `uses` must define `@ref`

.github/workflows/labels.yml
Discovered that it would be impossible to run two separate jobs, one for "global" labels and one for "local" labels, and to also specify `delete-other-labels: true`.
Consequently I have upstreamed the necessary changes:
* EndBug/label-sync#106
* EndBug/label-sync#107 (depends on DefinitelyTyped/DefinitelyTyped#58296)
~While we wait on those changes to be accepted we will utilize my fork.~ Changes have already been merged upstream!
┆Issue is synchronized with this [Jira Task](https://anaconda.atlassian.net/browse/CONDAORG-3)
=> Update labels action to properly combine global/local labels

.github/workflows/labels.yml
Addresses 2 issues:
1. checkout code before running label sync so the local `labels.yml` is accessible
2. check whether the local `labels.yml` even exists at all
=> Checkout before label sync & check for local file before using

.github/labels.yml
These four labels are uniquely defined for this repo, are these labels still of value to us or should they be deprecated, consolidated, or otherwise reworked?
| Label | Description |
|:-:|:--|
| ![`type::development`](https://img.shields.io/badge/-type::development-fff2cc) | related to developer environment setups |
| ![`type::github`](https://img.shields.io/badge/-type::github-fff2cc) | related to GitHub org administration |
| ![`type::hosting`](https://img.shields.io/badge/-type::hosting-fff2cc) | related to package hosting, e.g. conda-forge channel on anaconda.org |
cc: @jezdez
=> Define labels specific to conda/infra

.github/workflows/sync.yml
The commit title already contains the necessary info:
=> Remove unnecessary commit body

.github/global.yml
Include aliases for default GH labels. Identified in [label sync dryrun for conda/actions](https://github.com/conda/actions/runs/4925913928?check_suite_focus=true#step:4:656).
=> Include global label aliases

.github/workflows/boards.yml
Currently, when an issue is marked as https://github.com/conda/infra/labels/stale%3A%3Arecovered we have to manually notice this and then add it to the triaging board. This change intends to automate this with the following assumptions:
1. If an issue exists on the triaging, backlog, or sprint board and is labeled as https://github.com/conda/infra/labels/stale%3A%3Arecovered it should simply stay there
2. All other issues that are labeled with https://github.com/conda/infra/labels/stale%3A%3Arecovered should be added to the triaging board's **New** column so the triaging engineer can see it and address the issue
=> Add `stale::recovered` issues to triage board

.github/messages.yaml, .github/sync.yml, .github/workflows/stale.yml, .github/workflows/sync.yml
Moving stale workflow defined in conda/conda & conda/conda-build here to standardize across all repos. Since individual repos will have different stale/close messages I have moved those individual messages into a separate yaml file (`messages.yml`) so it can be customized per repo.
Opted to enable this stale workflow for **all** conda repos (except the two conda-build test repos), not just the selection identified previously for board automations.
=> Include stale workflow and update sync accordingly

.github/workflows/lock.yml, .github/workflows/stale.yml
If none of our stale/close/lock messages get set we provide a fallback value to make it clear that the value is missing.
=> Include fallback stale/close/lock message if none defined

.github/workflows/lock.yml, .github/workflows/stale.yml
Given the realization that composite GHA does not support dynamic outputs `read-yaml` had to be refactored and this change adjusts for those changes.
=> Use static output from `read-yaml`

.github/workflows/stale.yml
Updating the GitHub Actions `stale.yml` workflow for issues which have the `type::support` label on them.
=> Implement New Stale/Closed Timeline for `type::support` Issues

.github/workflows/stale.yml
Looks like [GHA doesn't like double quoted strings](https://docs.github.com/en/actions/learn-github-actions/expressions#:~:text=supported%20by%20JSON.-,string,single%20quote%20(%27%27).%20Wrapping%20with%20double%20quotes%20(%22)%20will%20throw%20an%20error.,-Example)
@beeankha my bad for suggesting wrong code in the first place!
Attempted fix for https://github.com/conda/infra/actions/runs/1972205555
=> Fix workflow syntax error

.github/sync.yml, .github/workflows/cla.yml
This was first implemented in https://github.com/conda/actions/pull/35 and relates to https://github.com/conda/infra/issues/538.
=> Add cla action.

.github/workflows/lock.yml, .github/workflows/stale.yml
Proposed solution for #547
This change does not impact the rate at which issues/PRs are marked as stale, closed, or locked but eliminates 2 of the 4 notifications/emails users receive today.
=> Remove close & lock messages

.github/sync.yml, .github/workflows/project.yml, .github/workflows/sync.yml
Working to replace triaging/backlog/sprint boards with one combined beta project.
This action simply automates adding all new issues and PRs to the beta project. Moving issues across the various views will be defined by the presence of labels.
Ref https://github.com/conda/infra/issues/515 https://github.com/conda/infra/issues/546
Stumbled across this action via [GitHub Roadmap](https://github.com/github/roadmap/issues/286) and https://github.com/itchysats/itchysats/pull/1383.
=> Adding issue/PR automation to add to the beta project

.github/global.yml
Adding label to collect SciPy 2022 sprint candidates.
=> Add `hack::SciPy2022` label

STYLEGUIDE.md
Continuation of https://github.com/conda/infra/pull/568#discussion_r930169578.
> **[@jezdez said:](https://github.com/conda/infra/pull/568#discussion_r930169578)**
> I'm not sure about [`# FUTURE`], one thing that Python, Django etc uses are the [`.. versionadded` and `.. versionchanged` Sphinx directives](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-versionadded), which Sphinx' autodoc can read in docstrings and next to module level variables.
>
> Could you look into if there is a pattern that is Sphinx/autodoc compatible that would allow us to bubble up the "future" information in the docs as well? Like a `.. future: Python 3.9+, replace with ...` for docstrings and `#: .. future: Python 3.9+, replace with ...` for [module or class attribute …
=> Add future directive

.github/rever.xsh
After merging #601 I realized the synced `rever.xsh` config had the project hardcoded as "conda", this changes this to properly extract the correct project name.
I've tested this by launching xonsh and sourcing rever.xsh:
```bash
$ xonsh .github/rever.xsh
$ xonsh
$ source .github/rever.xsh
$ $PROJECT
'infra'
```
=> Rever needs to use the correct project name

STYLEGUIDE.md
We need to standardize what we expect from docstrings. This PR contains 2 commits. The first commit extracts all URLs into reference links (which makes the markdown a little cleaner to read) and converts the policy indices into proper links. The second commit adds the docstring policy.
=> Specify docstrings in styleguide 

.github/global.yml
This pull request adds a new "documentation" section that we can use to better organize our "type::documentation" issues.
=> Adding a several new "documentation" tags

.github/dependabot.yml
As the infrastructure repo is the source of truth for the workflows that get synced to other repos in the conda organisation, it helps to keep the action versions used in those workflows updated by dependabot.
This opens the PRs currently visible here https://github.com/dbast/infrastructure/pulls
=> Add dependabot config for action updates

.github/sync/config.yml
While conda/actions have releases, they're not the same as rever releases, so there's no value in syncing the rever release instructions, the news snippet template, or the associated PR template.
=> Remove conda/actions from releases sync

.github/global.yml
Adds `type::deprecation` and updates `type::tech-debt` label description for clearer distinction. Also adds `tag::ux` to easily identify UX-related work.
Resolve #693
Resolve #694
=> Create new global labels for user experience and deprecation

.github/global.yml, HOW_WE_USE_GITHUB.md, README.md
Resolves issue #701 by renaming `sprint` label to `in-progress` and removing reference to sprint in description. Also includes updates to `readme` and `How We Use GitHub` documents to remove references to sprints.
Tasks:
=> Rename sprint label to in-progress (issue #701)

.github/global.yml
When attempting to run the label syncing I get the following error:
So I've sought to remove verbose language
=> Shorten duplicate label descriptions

.github/sync/rever.xsh
strip project name to avoid newline
Without this, we see "This project, conda
." with a newline or two between the project name and the period.
=> Update rever.xsh to avoid unwanted newline

.github/global.yml
We need to include dependabot's label https://github.com/conda/infrastructure/labels/dependencies otherwise it'll be deleted every time we run our label sync workflow and then readded when dependabot runs.
=> Add dependabot's label

HOW_WE_USE_GITHUB.md
This is a proposal to start requiring conda maintainers to use commit signing. I also added that we strongly recommend other contributors to do this as well.
=> Add requirement for conda maintainers to use commit signing

HOW_WE_USE_GITHUB.md
`HOW_WE_USE_GITHUB` is not rendering labels properly:
=> Fix Broken Links on Synced Docs

.github/workflows/stale.yml
`close-pr-reason` is actually not a valid input to the `actions/stale` GH Action. We keep getting warnings:
This was an accidental copy/paste of the `close-issue-reason` added in https://github.com/conda/infrastructure/pull/710
=> Remove invalid actions/stale input

.github/sync/config.yml
Sync out rever and release docs to conda-content-trust.
=> Add rever release to `conda-content-trust`

.github/sync/config.yml
conda-docs doesn't have releases so the news snippets serve no purpose.
https://github.com/conda/conda-docs/pull/910 removes unused news snippets.
=> Remove news snippets from conda-docs

.pre-commit-config.yaml
It would be helpful to see the `diff` for any pre-commit CI run changes; adding this as part of the pre-commit workflow.
=> Add `git-diff` hook to pre-commit CI runs

HOW_WE_USE_GITHUB.md
While testing conda's `24.3.x` release I noticed that one of the changes from [Updating Miniconda links #13572 PR](https://github.com/conda/conda/pull/13572) was reverted due to a document that's synced from this repo. This PR updates the miniconda link correctly on here so that any repos that have the `HOW_WE_USE_GITHUB.md` document will get synced/updated properly.
=> Update miniconda link for `HOW_WE_USE_GITHUB.md`

.github/ISSUE_TEMPLATE/0_bug.yml, .github/ISSUE_TEMPLATE/1_feature.yml, .github/ISSUE_TEMPLATE/2_documentation.yml, .github/ISSUE_TEMPLATE/epic.yml, .github/dependabot.yml, .github/global.yml, .github/labels.yml, .github/messages.yml, .github/sync/config.yml, .github/workflows/cla.yml, .github/workflows/issues.yml, .github/workflows/labels.yml, .github/workflows/lock.yml, .github/workflows/project.yml, .github/workflows/stale.yml, .github/workflows/sync.yml, .pre-commit-config.yaml, pyproject.toml, setup.cfg, sort_json.py
Just some spring cleaning:
- use `--implicit_start` to remove unnecessary `---` at the start of every yaml
- add `ruff` for our Python script (`sort_json.py`)
- add `pretty-format-toml` to keep `pyproject.toml` formatted nicely
=> Use `--implicit_start`, add `ruff` & `pretty-format-toml`

.github/workflows/issues.yml
The hash for `action-remove-labels` points to v1.3.0, not v1.2.0: https://github.com/actions-ecosystem/action-remove-labels/releases/tag/v1.3.0
=> Fix action-remove-labels version number

HOW_WE_USE_GITHUB.md
Fixes: #959 
I made the following changes to our templates:
- Removed two templates that are no longer relevant or useful: "slow solver" and "reinstall"
- Merged the two different Anaconda product related templates into a single one
- Added a new "General off topic" template to redirect user to conda community resources
=> Updates to answer templates

.github/workflows/lock.yml
Resolves #849.
The reasoning here is that some older tickets in the conda org have been waiting to be locked for a long time. We need to point out to new participants that there is a way forward instead of piling on, especially if the old issues were open-ended and no decision was made in the past. It's worth opening new issues instead.
=> Lower lockbot timeframe and add comment.

templates/HOW_WE_USE_GITHUB.md
Replace "conda maintainers" with "maintainers".
=> Remove conda specific reference for commit signing in `HWUG.md`

templates/config.yml, templates/releases/RELEASE.md
=> Use `canary_channel` instead of `canary-channel`

templates/releases/RELEASE.md
Since the community has moved away from Twitter and Matrix we might as well reflect this in the release announcements.
=> Update release announcements
