- .github/global.yml
- .github/workflows/labels.yml
Allow this repo to define its own separate local `labels.yml`.
> Rename global `labels.yml`

- .github/global.yml
Removing aliases that are causing syncing/deprecation conflicts.
> Remove label aliases

- .github/workflows/boards.yml
Fix for failing backlog action, see https://github.com/conda/conda/runs/4884389316
┆Issue is synchronized with this [Jira Task](https://anaconda.atlassian.net/browse/CONDAORG-6)
> Bump `issue-in-project` version

- .github/sync.yml
- .github/workflows/sync.yml
> Added remaining repos for syncing

- .github/workflows/sync.yml
Cleanup what the sync commits/PRs look like
> Include commit author & email

- .github/workflows/boards.yml
- .github/workflows/issues.yml
- .github/workflows/labels.yml
- .github/workflows/sync.yml
Working towards conda/conda#11085
> Check if the repo is a fork before running GHA

- .github/workflows/lock.yml
- .github/workflows/stale.yml
Suspecting that the dash in variable names is causing issues (wouldn't be surprising). Going ahead and replacing with underscores.
> Convert dashes to underscore

- .github/workflows/lock.yml
- .github/workflows/stale.yml
See https://github.com/conda/infra/actions/runs/1895768353
> GHA expressions use single quotes for strings

- .github/workflows/lock.yml
- .github/workflows/stale.yml
Resolves https://github.com/conda/conda/issues/11085
> Document which payload is being used

- .github/ISSUE_TEMPLATE/epic.yml
- .github/global.yml
- .github/sync.yml
Form contains 2 fields: a general description field and a list of linked issues/PRs.
[See issue form in action on my fork](https://github.com/kenodegard/infra/issues/new/choose)
Resolves #529
> Create Epic Issue Form

- .github/global.yml
> Add `[type::tests]` label

- .github/global.yml
Refs #531.
Refs #532.
Replaces #535.
> Minor tweak to the label.

- .github/workflows/labels.yml
- .github/workflows/lock.yml
- .github/workflows/stale.yml
- .pre-commit-config.yaml
> Add GH action/workflow checks

- .github/workflows/stale.yml
Let's be more aggressive with closing out stale issues and also be less generous with our exemptions.
> Close issues sooner

- sort_json.py
> Use python3 instead of python.

- STYLEGUIDE.md
Codifying our desire to adopt inclusive language in all conda org projects. The initial push is already well underway (see https://github.com/conda/conda/issues/11517 and https://github.com/conda/conda-build/issues/4494) and by codifying this we ensure we can point developers to this policy when future changes come up.
> Use inclusive language

- .clabot
Adding [topherocity](https://github.com/topherocity) to CLA signers.
> Add topherocity

- .clabot
Adding [hoechenberger](https://github.com/hoechenberger) to CLA signers.
> Add hoechenberger

- .clabot
Adding CLA signer [SamStudio8](https://github.com/SamStudio8).
> Add SamStudio8

- .clabot
Adding new user to CLA agreement list.
> Add skupr-anaconda

- .clabot
Adding CLA signee [razzlestorm](https://github.com/razzlestorm).
> Add razzlestorm

- .github/sync.yml
Sync basic GH setup to https://github.com/conda/conda-plugin-template.
> Sync to conda-plugin-template

- .github/RELEASE.md
- .github/TEMPLATE
- .github/rever.xsh
- .github/sync.yml
- .github/workflows/sync.yml
- RELEASE.md
As more of us are taking on the role of release manager, we need to publicize the current release process.
xref: https://github.com/conda/infra/issues/541
With this change, we will standardize the `rever.xsh` configuration for `conda`, `conda-build`, and `conda-package-handling`. We will also be syncing out the new `RELEASE.md` docs.
> Rever release config & docs

- .clabot
Adding CLA signee [QuantumMath](https://github.com/QuantumMath)
> Add QuantumMath

- .github/RELEASE.md
After going through the document with @travishathaway and @beeankha for https://github.com/conda/conda/pull/11844 we found a few necessary corrections.
Were there any other changes y'all think are necessary?
I've also added the rest of the release process, which is roughly outlined in the checklist template used for the Release Issue.
> Update `RELEASE.md` with input from conda 22.9.0 release

- .github/global.yml
To help us better categorize our spike issues, I propose adding a spike label.
Xref #611
> Adds a new label spike

- .clabot
Adding latest CLA signee [pkmooreanaconda](https://github.com/pkmooreanaconda).
> Add pkmooreanaconda

- .clabot
Add new CLA signee [consideRatio](https://github.com/consideratio)
> Add consideRatio

- .github/workflows/sync.yml
Include all sync files in the workflow trigger.
> Update & sort files triggering a sync

- .clabot
Adding CLA signature to "signed" list.
> Add Dario Curreri (dariocurr) to CLA signed list

- .clabot
... and remove `sv6002`, which is an invalid GH username.
> Add `sven6002` to CLA signed list

- .clabot
Adding [sanzoghenzo](https://github.com/sanzoghenzo) to CLA file.
> Adding sanzoghenzo to CLA file

- .clabot
Adding @AndrewVallette to cla file.
> Add AndrewVallette

- .clabot
Adding new contributor to CLA signed list.
> Add ReveStobinson to CLA signed list

- .github/sync/config.yml
communications is a new repo and it needs the standard short version of our Code of Conduct. This PR adds that repo to the list of repos that automatically get that.
> Add communications repo to the auto-generate CoC list

- .github/sync/config.yml
Sync Code of Conduct automatically to conda-lock via PRs.
> Sync Code of Conduct to conda-lock.

- .github/sync/config.yml
Refs https://github.com/conda/grayskull/issues/436.
> Sync CoC to grayskull.

- .clabot
Adding new user to the CLA agreement list.
> adding 12345 to cla

- .clabot
Adding CLA signee [rishabh11336](https://github.com/rishabh11336)
> Add CLA signee

- .clabot
Adding CLA singees [31Sanskrati](https://github.com/31Sanskrati) and [eltociear](https://github.com/eltociear)
Supersedes #692
> Add two new contributors

- .github/workflows/project.yml
Instead of automatically adding all PRs to the Planning project, add them to the new Review project.
Xref #696 
Supersedes #690
> Add PRs to a different project

- .clabot
Adding CLA signee [kalawac](https://github.com/kalawac)
> Add kalawac

- .github/workflows/issues.yml
Responds to [#709 ](https://github.com/conda/infrastructure/issues/709).
> Issues label update

- .github/global.yml
Resolves #704  
No other references to duplicates being only for issues: `HOW_WE_USE_GITHUB` contains sections that specifically talk about duplicate issues but these sections are not relevant to PRs.
> updated descriptions

- .github/ISSUE_TEMPLATE/2_documentation.yml
Add a documentation type issue template
Resolves #734
> Add a documentation type issue template

- .clabot
Adding "tl-hbk" to CLA agreement.
> Adding tl-hbk to CLA agreement

- .github/sync/RELEASE.md
Per the discussion from the March release retro we wish to cut the release branch a week earlier to allow for a distinct QA/testing period and to better facilitate a feature freeze.
> Update release process: create release issue & branch a week earlier

- .github/ISSUE_TEMPLATE/0_bug.yml
- .github/ISSUE_TEMPLATE/1_feature.yml
- .github/ISSUE_TEMPLATE/2_documentation.yml
- .github/ISSUE_TEMPLATE/epic.yml
- .github/dependabot.yml
- .github/global.yml
- .github/labels.yml
- .github/messages.yml
- .github/sync/config.yml
- .github/workflows/cla.yml
- .github/workflows/issues.yml
- .github/workflows/labels.yml
- .github/workflows/lock.yml
- .github/workflows/project.yml
- .github/workflows/stale.yml
- .github/workflows/sync.yml
- .pre-commit-config.yaml
> Enabling auto formatting for yaml files

- .clabot
> Add `sausagenoods` to contributor list

- .github/workflows/cla.yml
To fix https://github.com/conda/actions/pull/100
> Bump CLA action again.

- .github/workflows/stale.yml
Resolves https://github.com/conda/infrastructure/issues/759
> Update Stale Bot Timing

- .github/global.yml
Our pre-commit checks for this repository started failing. This is an attempt to fix that.
> Fix formatting of `.github/globals.yml` to make our yaml formatters happy 😄

- HOW_WE_USE_GITHUB.md
Sometimes we get issues in the conda project about the performance of the solver. This is an attempt to a have a standardized message we use for these types of issues going forward.
> Adding entry for the slow solvers

- .github/sync/RELEASE.md
Adding new information/updates gleaned from July's release process.
> Update RELEASE.md doc with more information

- .github/workflows/cla.yml
- .pre-commit-config.yaml
- setup.cfg
Inspired by https://github.com/conda/conda-docs/pull/877
> Adding codespell to pre-commit

- HOW_WE_USE_GITHUB.md
Comes from https://github.com/conda/conda/pull/12984/files#r1304178812
> Update message about classic solver

- .github/sync/config.yml
Use the same release process established for conda, conda-build, and others for pycosat.
> Sync rever release files to pycosat

- .clabot
This reverts commit 128f3d6d85bb35ed72e7fe6a5e056f2cb8e5c2dd.
Apologies for the hasty merge! Reverting due to no CLA signature.
> Revert "Adding CLA signee ThePrez (#821)"

- .github/ISSUE_TEMPLATE/0_bug.yml
- .github/ISSUE_TEMPLATE/1_feature.yml
- .github/ISSUE_TEMPLATE/2_documentation.yml
- .github/ISSUE_TEMPLATE/epic.yml
- CODE_OF_CONDUCT.md
- HOW_WE_USE_GITHUB.md
- README.md
The alert syntax has been updated and the old syntax was officially deprecated earlier in November 2023.
Xref https://github.com/orgs/community/discussions/16925
Xref [GitHub Markdown Docs](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts)
> Switch from old alert syntax to new syntax

- .github/sync/config.yml
- .github/workflows/sync.yml
In order for the documentation-issue-type template to show up in conda/conda this change is needed.
> Add documentation template in sync and workflow

- .github/sync/config.yml
Adds workflows to conda-package-streaming to automate issue handling (e.g. adding to the planning board, CLA checks, etc.)
Resolves #738
> Add conda-package-streaming to planning board

- .github/dependabot.yml
- .github/workflows/cla.yml
- .github/workflows/issues.yml
- .github/workflows/labels.yml
- .github/workflows/lock.yml
- .github/workflows/project.yml
- .github/workflows/stale.yml
- .github/workflows/sync.yml
- .pre-commit-config.yaml
- Add `check-dependabot` hook to pre-commit
- Limit dependabot's scope for GitHub Actions
- Switch GitHub Actions to use commit hashes instead of commit tags (dependabot will update tags to tags and hashes to hashes)
> Update pre-commit & dependabot config

- .github/ISSUE_TEMPLATE/epic.yml
Proposing edits and new fields in the "Epic" issue template to better capture information that will facilitate planning and prioritization efforts. Specifically, the new fields require the issue creator to clearly define the "what", "why", and "user impact" of the epic.
Resolves #909
> Update 'epic' issue template to better align with planning needs

- .github/workflows/cla.yml
- .github/workflows/issues.yml
- .github/workflows/labels.yml
- .github/workflows/lock.yml
- .github/workflows/project.yml
- .github/workflows/stale.yml
- .github/workflows/sync.yml
Since dependabot will update both the commit has and the version number (in the comment) lets have both!
> Include GHA version in comments

- .github/workflows/init.yml
- .github/workflows/update.yml
Followup to #937 after seeing `init.yml` workflow failure: https://github.com/conda/infrastructure/actions/runs/10182606224/job/28165567376
> Set git user globally

- .github/workflows/init.yml
Followup to #937 to fix `inti.yml` workflow failure: https://github.com/conda/infrastructure/actions/runs/10183457114/job/28168426270
> Fix relative path to upstream & downstream repos

- .github/workflows/init.yml
- .github/workflows/sync.yml
Followup to #978 
Missed two other references to the `sync/config.yml`.
> Correct `sync/config.yml` path

- .github/workflows/init.yml
- .github/workflows/update.yml
Just a small tweak since it's easy to misunderstand the PR otherwise
> Change PR titles

- .github/workflows/update.yml
Use the latest improvements to conda/actions! See sandbox run: https://github.com/conda-sandbox/upstream/pull/14
> Bump conda/actions to v24.8.0

- HOW_WE_USE_GITHUB.md
This follows the subsuming of the “issue sorter” team into the new conda maintainers team recently for the conda CLI project and fixing a misalignment with the multi-project reality of the conda org.
> Update who is responsible to sort issues.

- templates/config.yml
- templates/releases/RELEASE.md
Followup to #1066
We cannot use a "placeholder-x" parameter name since `[[ placeholder-x ]]` means `[[ placeholder - x ]]`. Need to use "placeholder_x" instead.
> Use `placeholder_x` instead of `placeholder-x`
